[package]
name = "ipinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipinfo = "0.3.1"
public-ip = "0.2.2"
tokio = { version = "1.18.2", features = ["full"] }